apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kubeguard-require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Requests and Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-cpu-memory-requests-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - kubeguard
      validate:
        message: "Containers must define CPU and memory requests and limits."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"